### PR TITLE
feat: full text rss feed

### LINKED ISSUE #27: Show full article content in RSS feed so we can share to R-bloggers
[R-bloggers](https://www.r-bloggers.com/) aggregates posts related to R to a wider audience; you can join by submitting your RSS feed for review, but they say:

> Submit a feed with full content, abstract/excerpts will not be accepted – this content will be shown in full in R-bloggers’ feed and email. Here are a few tips for how to get it done. On WordPress blogs you can fix this by going to settings -> reading -> “For each article in a feed, show” -> “Full text”. On Hugo blogs (blogdown blogs)  you can try the following:
Configure the default RSS template given here: https://gohugo.io/templates/rss/#the-embedded-rss-xml
replacing `{{ .Summary | html }}` with `{{ .Content | html }}`

Our [current feed](https://delphi.cmu.edu/blog/index.xml) only includes excerpts; can we edit the template as requested and test that the generated HTML looks good?

@sgratzl, would this be easy to do?

### PR DESCRIPTION
**Pull request by sgratzl**
closes #27

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
I've just tested this. It seems to work well, except that all the images embedded in the posts have the wrong links. For example, the most recent post's entry has images like this:

https://delphi.cmu.edu/blog/blog/post/2020-10-06-survey-wave-4_files/figure-html/mask-wearing-1.svg

Note the duplicate `/blog/blog/`.

Also it looks like no `<author>` is being listed for our posts. Maybe because we don't have `.Site.Author.email` and `.Site.Author.name` set, and we instead use the author listed on each post?

Otherwise it's looking pretty good.

**Comment by sgratzl** [comment]
@capnrefsmmat can you give it another try, please

**Comment by capnrefsmmat** [comment]
Sorry this took me so long to test. For some reason, the Hello World blog post is included incorrectly: it's included as raw HTML without escaping, which results in invalid XML. The About page (which we can probably just remove) is included the same way. All other posts are fine. Not sure what could cause this.

(To test, I rebased on main, then rebuilt the site.)

**Comment by sgratzl** [comment]
closing since part of the www-main

**Pull request closed without merging**
