### PR TITLE
add code-folding

### LINKED ISSUE #13: Support code folding in the blog
If we include an R code chunk and don't suppress the inclusion of the code, it appears as an inline code chunk right in the text.

R Markdown normally supports code folding, where the chunk initially appears hidden and a little "Code" button makes it appear. But Blogdown doesn't support that unless we manually add some JS to the theme. A couple links:

https://stackoverflow.com/questions/45360998/code-folding-in-bookdown
https://www.jepusto.com/code-folding-with-blogdown-academic/

Can we add something similar to the Hugo theme we're using, so we can include code chunks without disrupting the flow of the text?

### PR DESCRIPTION
**Pull request by sgratzl**
closes #13 

codefolding

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
When I preview this locally, I don't see the little dropdown arrow in your GIF, and I don't see anything in the code for it either. Is that meant to be included? It would be nice to have it.

**Comment by sgratzl** [comment]
re arrows: it uses the native https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details element. The arrows itself are rendered by the browser based on its local style. 

I was testing it with Chrome / Firefox.

**Comment by capnrefsmmat** [comment]
Ah, it's an interaction with CMU's CSS -- if I disable the `display:block` that it sets on `details`, then the triangle appears. You can see the rendered site here: http://rosmarus.refsmmat.com/blog/2020/08/11/covid-19-symptom-surveys-through-facebook/

(I'm using Firefox 79)

**Comment by sgratzl** [comment]
please try again

**Review by capnrefsmmat — APPROVED** [review]
Looks good in Firefox, Chrome, and Safari, thanks

**Pull request merged**
