### PR TITLE
Github Actions

### LINKED ISSUE #2: deployment build question
In the README it states several times that one shouldn't commit to the public directory. 

why not have the following workflow?

use a github action that builds the main branch and commits the built website into the gh-pages branch in the root directory.

an alternative would be to use netlify/vercel or another service doing a similar thing without commit built files to the repo

### PR DESCRIPTION
**Pull request by sgratzl**
closes #2 

create a Github action that will build the blog and push it to the `gh-pages` branch.

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
Nice automation. I guess we'll have to build in a list of required R packages in `R/prepare.R`?

I like the overall idea, but there's one snag. We'd like to deploy to delphi.cmu.edu rather than GitHub Pages, which means we'd use [github-deploy-repo](https://github.com/cmu-delphi/github-deploy-repo/) to deploy. It's configured by the `deploy.json` file (see the test-deploy branch on this repo), which is not smart enough to let us specify a specific branch to deploy from. It just clones the repo on the default branch and copies files from specified directories.

That means that building onto the `gh-pages` branch won't work with our automated deployment system.

Also: If we deploy this way, how do we check automatically that the blog has built successfully and all R code ran correctly, *without* deploying the site? Will we discover a missing R package only when the new post goes live?

**Comment by sgratzl** [comment]
> I like the overall idea, but there's one snag. We'd like to deploy to delphi.cmu.edu rather than GitHub Pages, which means we'd use [github-deploy-repo](https://github.com/cmu-delphi/github-deploy-repo/) to deploy. It's configured by the `deploy.json` file (see the test-deploy branch on this repo), which is not smart enough to let us specify a specific branch to deploy from. It just clones the repo on the default branch and copies files from specified directories.

one possible solution could be to create another git repository which this one is pushing its build into. So, instead of a separate branch it would be a different repo

**Comment by sgratzl** [comment]
> Also: If we deploy this way, how do we check automatically that the blog has built successfully and all R code ran correctly, _without_ deploying the site? Will we discover a missing R package only when the new post goes live?

the github action runs in any case on every branch. It will only push to the gh-pages branch if it is running from the main branch

**Comment by sgratzl** [comment]
> I like the overall idea, but there's one snag. We'd like to deploy to delphi.cmu.edu rather than GitHub Pages, which means we'd use [github-deploy-repo](https://github.com/cmu-delphi/github-deploy-repo/) to deploy. It's configured by the `deploy.json` file (see the test-deploy branch on this repo), which is not smart enough to let us specify a specific branch to deploy from. It just clones the repo on the default branch and copies files from specified directories.

when reading https://github.com/cmu-delphi/github-deploy-repo

there is the `--branch` option, isn't there?

**Comment by capnrefsmmat** [comment]
Yes, but I couldn't figure out how to get the automation to actually use that option -- but we can easily check with Brian and see if it's supported.

**Pull request merged**
