### PR TITLE
theming

### LINKED ISSUE #1: Add navbar and CSS styling to Delphi blog
@sgratzl , can you help us make this blog match the COVIDcast website as much as possible, before its release on Tuesday?

This includes:

- [ ] Adding the navbar
- [ ] "some executive direction on typography so font faces, sizes, header conventions, etc match throughout" - @zackchase 

I presume we could borrow most of this from https://www.cmu.edu/common/standard-v6/css/main.min.css

@capnrefsmmat says: "We have the ability to use any [Hugo theme](https://themes.gohugo.io/tags/blog/) or build our own [from a minimal template](https://github.com/yihui/hugo-xmin), as well as modifying the current theme however we want; I just picked this one because it was minimal, clean, and easy to tweak."

### PR DESCRIPTION
**Pull request by sgratzl**
based on #3 

closes #1 

image

image

image

### CODE REVIEW

**Comment by adamperer** [comment]
Nice work, Sam

@zackchase @capnrefsmmat Does this theming address what you were looking for?

**Comment by zackchase** [comment]
Hi all, looks like it's getting there but a few issues! 

1.  The spacing between headings appears to be weird right now: "A Little Bit About Us" right now has more space above than below. 
2. The post needs some share links under the title, above the article: see https://github.com/cmu-delphi/delphi-blog/issues/5
3. We need to fix the Nav links. We need to have the *home on the far left*. We also should make these all one words, multiword navs look sloopy, I'd go with:
    * Delphi    
    * Map
    * API
    * Blog
    * Contact

Right now Delphi home really is a static "about" page now, why do we need another about page? And if we have one, then what goes on the Delphi page.

**Comment by adamperer** [comment]
> 3. We need to fix the Nav links. 

The links should match the links in this nav bar here -- so it looks consistent when you go from one tab to another:
https://cms-staging.andrew.cmu.edu/covid/index.html

Any objections @zackchase?

**Comment by adamperer** [comment]
> 1. The spacing between headings appears to be weird right now: "A Little Bit About Us" right now has more space above than below.

I agree the spacing needs improvement (also pointed out by @ryantibs in Slack).  

- [ ] There is too much space between the author names and the content of the blog post.  
- [ ] Too little space between the divider and the date of the next post
- [ ] Perhaps too much room between blog post title and authors?

**Comment by sgratzl** [comment]
addressed the theming issues:

regarding menu and share buttons: imo that should be part of a separate PR

image

**Review by capnrefsmmat — APPROVED** [review]
Approving so we can merge and base future work on top of this

**Pull request merged**
