### PR TITLE
Blog post on the API

### PR DESCRIPTION
**Pull request by krivard**
Roughly based on the CDC talk from Ryan and some of the engineering onboarding documentation.

Topics:
* open source, open data
* unique data relationships
* our datasets vs the severity pyramid (@RoniRos do you have a nice citation for the severity pyramid if people want to know more about it?)
* data schema
* data versioning and its importance for forecasting
* clients, including brief demos
* the extract-transform-load pipeline, with hooks for ultimately releasing the indicators codebase open-source
* glossary of terms

Conclusion is still rough but we're ready for feedback & edits.

### CODE REVIEW

**Comment by RoniRos** [comment]
> @RoniRos do you have a nice citation for the severity pyramid if people want to know more about it?

Not really, it is a very basic concept in epidemiology.

**Comment by ryantibs** [comment]
Hi @capnrefsmmat @krivard, one more thought, which I didn't write into the HTML comments, but struck me now: we kind of casually wander into the way in which they can get data from the API, going back and forth between describing important aspects and the background and scientific importance of the data sources, and the more practical "how to".

Perhaps, especially if we're treating this post as one of our premier selling points to convince people to start using our API, we should make the "how to" part more explicitly marked and more obvious.  That is, have one single section which is more explicit and hands-on about: 

1. navigating the metadata to figure out the names of what they want
2. writing code to fetch the data they want (with a little bit more depth about what all the options are)
3. understanding the output (with a little bit more depth about its format)
4. understanding the utilities (plots, correlations, etc.) they have available to them.

Yes this info is present in large part in the R vignettes (and maybe also the Python documentation)?  But I think this blog post could still to a nice job consolidating and walking through it.  What do you think?  Or, we could write a separate post on the client packages and give the more hands-on tutorial there?

**Comment by capnrefsmmat** [comment]
I think we should remember that blog posts are meant to be quick, easy to for us to write, and easy for a reader to digest in a few minutes to learn about what the COVIDcast project is doing. Readers want a short post that gets them interested, and likely don't have the patience to read a long detailed post all the way through.

In other words, I think the post should make someone go "Huh, I should try using this API, it sounds useful" rather than overwhelming them with detail so they skip to the end.

So I think the R package vignette should be expanded, and the Python documentation should be polished, and the role of a future API client blog post should primarily be advertising, rather than as a surrogate manual. Then we can invest extra effort into improving vignettes and documentation to cover the topics you describe.

**Comment by ryantibs** [comment]
I agree with everything you said, but I still don't arrive at the conclusion that we can't put a short tutorial in this blog post.  It doesn't have to be longer than a couple paragraphs total.  Let me pitch my suggestion a different way: just show people a simple concrete example with "the 3 steps", and mark it very clearly as its own section.  That way they know where to go if they want to learn how to use what we've built.  Steps:

1. explore the metadata: walk them through how you'd find the right signal name for the Facebook CLI-in-community signal (or just pick any one for an example)
2. construct an API call: walk them through how you'd fetch data from the API, in the R or Python client, or via query string
3. understand the output: walk them through what the output format means, and broadly what they can do with it.

(We can quick allude briefly to all the things you can do with the output, but we can just link out to the vignettes or documentation rather than explaining it in detail.  And we can still think about doing a single blog post on the client packages if we want, when they're a bit more developed.)  

Making the R vignettes and Python documentation even *more* comprehensive just further motivates for me the value of putting this short tutorial in the blog post.  Because this will be very different: just very short and sweet, to help get somebody started really quickly.  What do you think?

**Comment by capnrefsmmat** [comment]
I pushed a new commit that takes a small step in that direction. The "Accessing the API" section now explains how you'd find a signal in the documentation and how you'd go about downloading it either from the Export Data tool or in R/Python. I deferred the JSON method to the end, because it's the least user-friendly.

I don't want to get into much more depth than this, because it will start replicating the package vignettes, and I'd simply like to make those better. But I think this provides a nice little introduction (and I bet a lot of people will like the Export Data button much better than the other options!).

Also, my other consideration is just that I'd like to get this post out soonish, and writing a new tutorial will take more time than I have available.

**Comment by ryantibs** [comment]
Nice job!  I think it looks good, was more or less what I was looking for.  

@capnrefsmmat Let me know if you'd like me to take a look top-to-bottom again, assuming you've finished your revisions?  Or maybe it makes sense for @krivard and/or @zackchase to make their pass first, then I can look after.

**Comment by capnrefsmmat** [comment]
I think I'm done with changes I know of, so one of you can take a pass.

**Pull request merged**
